"""Stable string enums shared across gateway layers."""

from __future__ import annotations

from enum import StrEnum


class RequestType(StrEnum):
    ACCESS_REQUEST = "ACCESS_REQUEST"
    PROCUREMENT_REQUEST = "PROCUREMENT_REQUEST"
    MAINTENANCE_REQUEST = "MAINTENANCE_REQUEST"
    POLICY_INQUIRY = "POLICY_INQUIRY"
    UNKNOWN = "UNKNOWN"


class DomainTemplate(StrEnum):
    ACCESS = "ACCESS"
    PROCUREMENT = "PROCUREMENT"
    MAINTENANCE_LITE = "MAINTENANCE_LITE"
    POLICY = "POLICY"
    UNKNOWN = "UNKNOWN"


class AgentRunStatus(StrEnum):
    CREATED = "CREATED"
    CLASSIFYING = "CLASSIFYING"
    DECISION_VALIDATION = "DECISION_VALIDATION"
    NEEDS_USER_INPUT = "NEEDS_USER_INPUT"
    TOOL_PLANNING = "TOOL_PLANNING"
    TOOL_VALIDATION = "TOOL_VALIDATION"
    EXECUTING_READ_TOOLS = "EXECUTING_READ_TOOLS"
    POLICY_CHECK = "POLICY_CHECK"
    WAITING_FOR_APPROVAL = "WAITING_FOR_APPROVAL"
    EXECUTING_ACTION = "EXECUTING_ACTION"
    COMPLETED = "COMPLETED"
    FAILED_PROVIDER = "FAILED_PROVIDER"
    FAILED_VALIDATION = "FAILED_VALIDATION"
    FAILED_TOOL = "FAILED_TOOL"
    REJECTED = "REJECTED"
    NEEDS_MANUAL_REVIEW = "NEEDS_MANUAL_REVIEW"


class RiskLevel(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class ToolType(StrEnum):
    READ_ONLY = "READ_ONLY"
    STATE_CHANGING = "STATE_CHANGING"
    APPROVAL = "APPROVAL"
    AUDIT = "AUDIT"


class ToolCallStatus(StrEnum):
    PROPOSED = "PROPOSED"
    VALIDATED = "VALIDATED"
    EXECUTING = "EXECUTING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    REJECTED = "REJECTED"
    WAITING_FOR_APPROVAL = "WAITING_FOR_APPROVAL"


class ApprovalStatus(StrEnum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"


class AuditEventType(StrEnum):
    RUN_CREATED = "RUN_CREATED"
    PROVIDER_SELECTED = "PROVIDER_SELECTED"
    DECISION_VALIDATED = "DECISION_VALIDATED"
    TOOL_PROPOSED = "TOOL_PROPOSED"
    TOOL_VALIDATED = "TOOL_VALIDATED"
    TOOL_EXECUTED = "TOOL_EXECUTED"
    POLICY_CHECKED = "POLICY_CHECKED"
    APPROVAL_REQUESTED = "APPROVAL_REQUESTED"
    APPROVAL_DECIDED = "APPROVAL_DECIDED"
    RUN_COMPLETED = "RUN_COMPLETED"
    RUN_FAILED = "RUN_FAILED"


class ProviderName(StrEnum):
    MOCK = "MOCK"
    GIGACHAT = "GIGACHAT"
    YANDEX = "YANDEX"
