"""Maintenance-lite demo-template tools and schemas."""

from enterprise_ai_tool_gateway.maintenance_lite.schemas import (
    AssetCriticality,
    AssetInfo,
    AssetStatus,
    CheckMaintenancePolicyInput,
    ClassifyMaintenanceSeverityInput,
    ClassifyMaintenanceSeverityOutput,
    CreateWorkOrderDraftInput,
    CreateWorkOrderDraftOutput,
    ExistingMaintenanceTicket,
    GetAssetInfoInput,
    GetAssetInfoOutput,
    GetMaintenanceRequesterProfileInput,
    GetMaintenanceRequesterProfileOutput,
    GetOpenMaintenanceTicketsInput,
    GetOpenMaintenanceTicketsOutput,
    MaintenancePolicyOutput,
    MaintenancePolicyRule,
    MaintenanceRequesterProfile,
    MaintenanceRequesterStatus,
    MaintenanceSeverity,
    MaintenanceTicketStatus,
)
from enterprise_ai_tool_gateway.maintenance_lite.tools import (
    get_maintenance_tool_definitions,
    register_maintenance_tools,
)

__all__ = [
    "AssetCriticality",
    "AssetInfo",
    "AssetStatus",
    "CheckMaintenancePolicyInput",
    "ClassifyMaintenanceSeverityInput",
    "ClassifyMaintenanceSeverityOutput",
    "CreateWorkOrderDraftInput",
    "CreateWorkOrderDraftOutput",
    "ExistingMaintenanceTicket",
    "GetAssetInfoInput",
    "GetAssetInfoOutput",
    "GetMaintenanceRequesterProfileInput",
    "GetMaintenanceRequesterProfileOutput",
    "GetOpenMaintenanceTicketsInput",
    "GetOpenMaintenanceTicketsOutput",
    "MaintenancePolicyOutput",
    "MaintenancePolicyRule",
    "MaintenanceRequesterProfile",
    "MaintenanceRequesterStatus",
    "MaintenanceSeverity",
    "MaintenanceTicketStatus",
    "get_maintenance_tool_definitions",
    "register_maintenance_tools",
]
