"""Workflow events accepted by the AgentRun state kernel."""

from __future__ import annotations

from enum import StrEnum


class WorkflowEventType(StrEnum):
    START_CLASSIFICATION = "START_CLASSIFICATION"

    PROVIDER_DECISION_RECEIVED = "PROVIDER_DECISION_RECEIVED"
    PROVIDER_FAILED = "PROVIDER_FAILED"

    DECISION_VALID = "DECISION_VALID"
    DECISION_MISSING_INPUT = "DECISION_MISSING_INPUT"
    DECISION_INVALID = "DECISION_INVALID"
    MANUAL_REVIEW_REQUIRED = "MANUAL_REVIEW_REQUIRED"

    TOOL_PLAN_CREATED = "TOOL_PLAN_CREATED"
    NO_TOOLS_REQUIRED = "NO_TOOLS_REQUIRED"
    TOOL_PLAN_VALID = "TOOL_PLAN_VALID"
    TOOL_PLAN_INVALID = "TOOL_PLAN_INVALID"

    READ_TOOLS_EXECUTED = "READ_TOOLS_EXECUTED"
    TOOL_EXECUTION_FAILED = "TOOL_EXECUTION_FAILED"

    POLICY_ALLOWED_NO_ACTION = "POLICY_ALLOWED_NO_ACTION"
    POLICY_ALLOWED_ACTION = "POLICY_ALLOWED_ACTION"
    POLICY_REQUIRES_APPROVAL = "POLICY_REQUIRES_APPROVAL"
    POLICY_REJECTED = "POLICY_REJECTED"
    POLICY_MANUAL_REVIEW = "POLICY_MANUAL_REVIEW"

    APPROVAL_APPROVED = "APPROVAL_APPROVED"
    APPROVAL_REJECTED = "APPROVAL_REJECTED"

    ACTION_EXECUTED = "ACTION_EXECUTED"
    ACTION_FAILED = "ACTION_FAILED"

    USER_INPUT_RECEIVED = "USER_INPUT_RECEIVED"
